/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.scheduling.annotation.EnableScheduling;

@SpringBootApplication
@EnableScheduling
public class WeatherMonitoringSystemApplication {

    public static void main(String[] args) {
        SpringApplication.run(WeatherMonitoringSystemApplication.class, args);
    }

    public String getGreeting() {
        return "Hello, Weather Monitoring System!";
    }
}
