/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import org.junit.jupiter.api.Test; // Use JUnit 5 imports
import static org.junit.jupiter.api.Assertions.*;

public class AppTest {
    @Test public void appHasAGreeting() {
        WeatherMonitoringSystemApplication classUnderTest = new WeatherMonitoringSystemApplication();
        assertNotNull("app should have a greeting", classUnderTest.getGreeting());
    }
}
